# Generated by Django 4.2.1 on 2023-05-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stock_user_stock_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='list_name',
            field=models.CharField(default=list, max_length=100),
            preserve_default=False,
        ),
    ]
